apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: searxng
  namespace: ai
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  serviceName: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
      - name: searxng
        image: searxng/searxng:latest@sha256:3e11c8454e62de8b5cbb5ba7f5b9568a6eb3d40414af1a884d435bf79b3bfe9f
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/searxng
          name: searxng-volume
      volumes:
      - name: searxng-volume
        persistentVolumeClaim:
          claimName: searxng-data-pvc
