apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  serviceName: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest@sha256:075bc77361e6466f5cd546c9d97646428cc1f26d4b355991e8f66d0ffbc7c15a
        ports:
        - containerPort: 8096
        env:
        - name: TZ
          value: Africa/Johannesburg
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: tvshows
            mountPath: /tvshows
          - name: movies
            mountPath: /movies
          - name: music
            mountPath: /music
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: tvshows
          hostPath:
            path: /mnt/media/tvshows
        - name: movies
          hostPath:
            path: /mnt/media/movies
        - name: music
          hostPath:
            path: /mnt/media/music
