apiVersion: v1
kind: ConfigMap
metadata:
    name: values
    namespace: flux-system
data:
    values.yaml: |-
        deployment:
          kind: DaemonSet
        service:
          loadBalancerIP: 10.4.20.51
          externalTrafficPolicy: Local
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          enabled: true
          name: traefik-gateway
          listeners:
            web:
              protocol: HTTP
              namespacePolicy:
                from: All
            websecure:
              protocol: HTTPS
              namespacePolicy:
                from: All
              tls:
                certificateRefs:
                - kind: Secret
                  name: letsencrypt-prod
        gatewayClass:
          enabled: true
          name: traefik-gateway-class