apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readarr
  namespace: media
  labels:
    app: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  serviceName: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      containers:
      - name: readarr
        image: lscr.io/linuxserver/readarr:develop@sha256:d71c575745ab4579ae0dbb4f91244cf9a74d7085d28a927218146466f8e6418c
        ports:
        - containerPort: 8787
        env:
        - name: TZ
          value: Africa/Johannesburg
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: books
            mountPath: /books
          - name: downloads
            mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: readarr-pvc
        - name: books
          hostPath:
            path: /mnt/media/books
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /mnt/media/downloads
            type: DirectoryOrCreate
