apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql@sha256:a6f748d96bfa4d361df5e9284eba041c475e7ff26c1358f8f189969437ebdb9b
        ports:
        - containerPort: 10051
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_postgres_password
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: database_url
