apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-survival
  namespace: minecraft
  labels:
    app: minecraft-bedrock-survival
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-survival
  serviceName: minecraft-survival
  template:
    metadata:
      labels:
        app: minecraft-survival
    spec:
      containers:
      - name: minecraft-survival
        image: itzg/minecraft-bedrock-server:2026.5.3@sha256:d0aa4e6726adba217e6a38fcc56320ac948272f06fc21b8a0788dc8f56edaad7
        imagePullPolicy: Always
        ports:
        - containerPort: 19132
          protocol: UDP
        env:
        - name: DIFFICULTY
          value: easy
        - name: EULA
          value: "true"
        - name: GAMEMODE
          value: survival
        - name: ONLINE_MODE
          value: "false"
        - name: SERVER_NAME
          value: minecraft-survival
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
