apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-survival
  namespace: minecraft
  labels:
    app: minecraft-bedrock-survival
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-survival
  serviceName: minecraft-survival
  template:
    metadata:
      labels:
        app: minecraft-survival
    spec:
      containers:
      - name: minecraft-survival
        image: itzg/minecraft-bedrock-server:2026.6.2@sha256:8e045b7b3a4d43ad70459356874a262fd63e2f2ce82d5b0c9e5e956233e9d771
        imagePullPolicy: Always
        ports:
        - containerPort: 19132
          protocol: UDP
        env:
        - name: DIFFICULTY
          value: easy
        - name: EULA
          value: "true"
        - name: GAMEMODE
          value: survival
        - name: ONLINE_MODE
          value: "false"
        - name: SERVER_NAME
          value: minecraft-survival
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
