apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  serviceName: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.17@sha256:b5670a3adb0f8a8b0f277feeaa69a5fbe3869ba4bb9fa7c0f0764c3b3f0e698f
        ports:
        - containerPort: 8989
        env:
        - name: TZ
          value: Africa/Johannesburg
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: tvshows
            mountPath: /tvshows
          - name: downloads
            mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-pvc
        - name: tvshows
          hostPath:
            path: /mnt/media/tvshows
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /mnt/media/downloads
            type: DirectoryOrCreate
