apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phpipam-mysql
  namespace: phpipam
  labels:
    app: phpipam-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpipam-mysql
  serviceName: phpipam-mysql
  template:
    metadata:
      labels:
        app: phpipam-mysql
    spec:
      containers:
      - name: phpipam-mysql
        image: mysql:9.2@sha256:146682692a3aa409eae7b7dc6a30f637c6cb49b6ca901c2cd160becc81127d3b
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phpipam-secret
              key: mysql_root_password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: phpipam-mysql-volume
      volumes:
      - name: phpipam-mysql-volume
        persistentVolumeClaim:
          claimName: phpipam-data-pvc
