apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: ai
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  serviceName: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest@sha256:0ff452f6a4c3c5bb4ab063a1db190b261d5834741a519189ed5301d50e4434d1
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
          protocol: TCP
        env:
        - name: OLLAMA_KEEP_ALIVE
          value: "24h"
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-volume
      volumes:
      - name: ollama-volume
        persistentVolumeClaim:
          claimName: ollama-data-pvc
