apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: ai
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  serviceName: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest@sha256:5a5d014aa774f78ebe1340c0d4afc2e35afc12a2c3b34c84e71f78ea20af4ba3
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
          protocol: TCP
        env:
        - name: OLLAMA_KEEP_ALIVE
          value: "24h"
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-volume
      volumes:
      - name: ollama-volume
        persistentVolumeClaim:
          claimName: ollama-data-pvc
