apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: searxng
  namespace: ai
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  serviceName: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
      - name: searxng
        image: searxng/searxng:latest@sha256:dacc93763984cc18ed0e8fbd58a7a8f2ae8417da11dac9ddb43a0cb6d85e06dd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/searxng
          name: searxng-volume
      volumes:
      - name: searxng-volume
        persistentVolumeClaim:
          claimName: searxng-data-pvc
