apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phpipam-mysql
  namespace: phpipam
  labels:
    app: phpipam-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpipam-mysql
  serviceName: phpipam-mysql
  template:
    metadata:
      labels:
        app: phpipam-mysql
    spec:
      containers:
      - name: phpipam-mysql
        image: mysql:9.4@sha256:91447968e66961302339ec4dc4d385f5e1a957d98e63c7d52ecf8b1de0907346
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phpipam-secret
              key: mysql_root_password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: phpipam-mysql-volume
      volumes:
      - name: phpipam-mysql-volume
        persistentVolumeClaim:
          claimName: phpipam-data-pvc
