apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix
  labels:
    app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-apache-pgsql@sha256:9b5ad53c684c9f5d7b15c626e22e3d2c97c2b0b2b05ce811d1a8fe42416cd01b
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_postgres_password
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: database_url
        - name: ZBX_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: server_url
