apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-creative
  namespace: minecraft
  labels:
    app: minecraft-creative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-creative
  serviceName: minecraft-creative
  template:
    metadata:
      labels:
        app: minecraft-creative
    spec:
      containers:
      - name: minecraft-creative
        image: itzg/minecraft-bedrock-server:2026.6.2@sha256:8e045b7b3a4d43ad70459356874a262fd63e2f2ce82d5b0c9e5e956233e9d771
        imagePullPolicy: Always
        ports:
        - containerPort: 19132
          protocol: UDP
        env:
        - name: DIFFICULTY
          value: peaceful
        - name: EULA
          value: "true"
        - name: GAMEMODE
          value: creative
        - name: ONLINE_MODE
          value: "false"
        - name: SERVER_NAME
          value: minecraft-creative
        volumeMounts:
        - mountPath: data
          name: vol1
          subPath: data
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: minecraft-bedrock-creative-data
