name: Host 02 Terraform CD

on:
  workflow_dispatch: 
  pull_request:
    paths:
      - 'terraform/host_02/**'
    
permissions:
  contents: write
  issues: write

jobs:
  init_and_plan:
    name: Terraform Init and Plan
    runs-on: Self-Hosted

    outputs:
      planExitcode: ${{ steps.terraformPlan.outputs.exitcode }}

    steps:

      - name: Checkout 🔔
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Map Secrets to Environment Variables 🗺️ 
        uses: oNaiPs/secrets-to-env-action@75f319b3c8c926ac2eabcca34daa6cf531daf32f # v1.8
        with:
            secrets: ${{ toJSON(secrets) }}        

      - name: Replace Tokens 🪙
        uses: cschleiden/replace-tokens@4d5a042c84c3568b3858b7af9394923d2d5195c9 # v1.3
        with:
          files: '["./terraform/host_02/**/*"]'

      - name: Install Terraform ⛰️
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Init 🏃
        id: terraformInit
        run: terraform init
        working-directory: ./terraform/host_02

      - name: Terraform Plan 🗺️
        id: terraformPlan
        run: |
          terraform plan -input=false -no-color -out ${{ github.sha }}.tfplan -detailed-exitcode 
        working-directory: ./terraform/host_02

      - name: Cache Terraform Plan 📦
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ./terraform/host_02/**
          key: ${{ github.sha }}

  apply:
    name: Terraform Apply
    needs:
      - init_and_plan
    if: needs.init_and_plan.outputs.planExitcode == 2
    runs-on: Self-Hosted

    steps:

      - name: Manual Approval 🚦
        uses: trstringer/manual-approval@9f5e5d6bc511762e17f849775a3c56bdea6b4493 # v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: data-tangles
          minimum-approvals: 1
          issue-title: "Terraform Apply"
          issue-body: "Please approve or deny the Terraform Apply operation"
          exclude-workflow-initiator-as-approver: false

      - name: Checkout 🔔
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Restore Terraform Plan 🗺️
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ./terraform/host_02/**
          key: ${{ github.sha }}

      - name: Install Terraform ⛰️
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Apply 🚀
        run: terraform apply ${{ github.sha }}.tfplan
        working-directory: ./terraform/host_02

