apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql@sha256:c8db24a3fc509ea4b1a3d9f4ef197e1ee46f2656f586c3c5f9014ca6de61804b
        ports:
        - containerPort: 10051
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_postgres_password
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: database_url
